const JOBS = Object.freeze({
  DRK: {
    NAME: 'Dark Knight',
    ACRONYM: 'DRK',
    ROLE: 'Tank',
    ROLE_ALT: 'Tank',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  PLD: {
    NAME: 'Paladin',
    ACRONYM: 'PLD',
    ROLE: 'Tank',
    ROLE_ALT: 'Tank',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  WAR: {
    NAME: 'Warrior',
    ACRONYM: 'WAR',
    ROLE: 'Tank',
    ROLE_ALT: 'Tank',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  WHM: {
    NAME: 'White Mage',
    ACRONYM: 'WHM',
    ROLE: 'Healer',
    ROLE_ALT: 'Healer',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  SCH: {
    NAME: 'Scholar',
    ACRONYM: 'SCH',
    ROLE: 'Healer',
    ROLE_ALT: 'Healer',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  AST: {
    NAME: 'Astrologian',
    ACRONYM: 'AST',
    ROLE: 'Healer',
    ROLE_ALT: 'Healer',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  DRG: {
    NAME: 'Dragoon',
    ACRONYM: 'DRG',
    ROLE: 'DPS',
    ROLE_ALT: 'Melee Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  MNK: {
    NAME: 'Monk',
    ACRONYM: 'MNK',
    ROLE: 'DPS',
    ROLE_ALT: 'Melee Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  NIN: {
    NAME: 'Ninja',
    ACRONYM: 'NIN',
    ROLE: 'DPS',
    ROLE_ALT: 'Melee Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  SAM: {
    NAME: 'Samurai',
    ACRONYM: 'SAM',
    ROLE: 'DPS',
    ROLE_ALT: 'Melee Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  BRD: {
    NAME: 'Bard',
    ACRONYM: 'BRD',
    ROLE: 'DPS',
    ROLE_ALT: 'Ranged Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  MCH: {
    NAME: 'Machinist',
    ACRONYM: 'MCH',
    ROLE: 'DPS',
    ROLE_ALT: 'Ranged Physical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  BLM: {
    NAME: 'Black Mage',
    ACRONYM: 'BLM',
    ROLE: 'DPS',
    ROLE_ALT: 'Ranged Magical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  SMN: {
    NAME: 'Summoner',
    ACRONYM: 'SMN',
    ROLE: 'DPS',
    ROLE_ALT: 'Ranged Magical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
  RDM: {
    NAME: 'Red Mage',
    ACRONYM: 'RDM',
    ROLE: 'DPS',
    ROLE_ALT: 'Ranged Magical DPS',
    BIT: '',
    ICON: '',
    COLOR: '',
  },
})

export default JOBS